### ISSUE TITLE
Intercepts in OTP20

### ISSUE THREAD

**Issue by martinsumner** [basho/riak_test#1333]
The `verify_corruption_filtering` test fails consistently in bitcask on `develop-3.0`.

When running the test bitcask constantly crashes during the leave:

```
exception error: {{badfun,#Fun<riak_kv_bitcask_backend.1.70625586>},[{bitcask,'-fold/6-fun-0-',11,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask.erl"},{line,411}]},{bitcask_fileops,fold_int_loop,5,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask_fileops.erl"},{line,558}]},{bitcask_fileops,fold_file_loop,8,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask_fileops.erl"},{line,716}]},{bitcask_fileops,fold,3,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask_fileops.erl"},{line,390}]},{bitcask,subfold,3,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask.erl"},{line,522}]},{bitcask_nifs,keydir_frozen,4,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/bitcask/src/bitcask_nifs.erl"},{line,272}]},{riak_kv_bitcask_backend_orig,'-fold_objects_orig/4-fun-1-',5,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/riak_kv/src/riak_kv_bitcask_backend.erl"},{line,355}]},{riak_kv_worker,handle_work,3,[{file,"/Users/martinsumner/dbroot/basho/riak/_build/default/lib/riak_kv/src/riak_kv_worker.erl"},{line,46}]}]}
```

This bad function is a function passed in from the `riak_kv_bitcask_backend` module on startup.  This module (although not the function) though is dynamically changed during the test (following startup) to add intercept functions.

If I move the key_transform function into a separate, dedicated module - the test will pass.

It looks like adding intercepts causes problems to functions in other repos that referenced back to the edited module (even if the function itself is not changed).

**Comment by martinsumner** [comment]
@ThomasArts I'm not sure what to do about this.  I can fix it by making the change mentioned to the code (move the key_transform into a separate module outside of riak_kv_bitcask_backend module) - but it seems wrong to structure the code like this just to make an intercept in a single test work.

Any suggestions?

**Comment by martinsumner** [comment]
This is the branch with the changes to make the test pass: https://github.com/basho/riak_kv/tree/develop-3.0-keytransfor

**Comment by nsaadouni** [comment]
Can you not add the key_transform into the riak_kv_bitcask_backend_intercepts, and point it to the original instead?

I think the problem is coming from the intercept changing the module name for the key_transform function, yet in bitcask it has it as a dynamic fun pointed to ?MODULE:key_transform_1 

?MODULE = riak_kv_bitcask_backend

**Comment by martinsumner** [comment]
Do you mean an intercept like this in `riak_kv_bitcask_backend_intercepts`?

```
passthrough_key_transform(Key) ->
    ?M:get_orig(Key).
```

**Comment by martinsumner** [comment]
@ThomasArts - can you review the intercept code, and confirm that multiple intercepts (on the same module) is implemented in a safe way?

**Comment by UlfNorell** [comment]
Multiple calls to `rt_intercept:add/2` on the same module is *not* implemented safely.

The problem is that multiple adds will load the module multiple times, and since the runtime system only keeps two versions of a module around, the original code will be unloaded. This means that any funs using the original code will stop working. This is what's causing the `badfun` exception.

See https://erlang.org/doc/reference_manual/code_loading.html#code-replacement

The simple solution is to not make multiple calls to `rt_intercept:add/2` with the same module. In this particular case:
```erlang
         rt_intercept:add(Node, {riak_kv_bitcask_backend,
                                 [{{get, 3}, corrupting_get},
                                  {{put, 5}, corrupting_put}]}),
```

It possible that there is some low-level magic that could be used to have it drop the modified code instead of the original code on the second call, but this is beyond my knowledge of Erlang.
